// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: phonebook/phonebook.proto

package phonebook

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "grpc-http-server/pb/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePhoneRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *CreatePhoneRecordRequest) Reset() {
	*x = CreatePhoneRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phonebook_phonebook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePhoneRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneRecordRequest) ProtoMessage() {}

func (x *CreatePhoneRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebook_phonebook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneRecordRequest.ProtoReflect.Descriptor instead.
func (*CreatePhoneRecordRequest) Descriptor() ([]byte, []int) {
	return file_phonebook_phonebook_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePhoneRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePhoneRecordRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreatePhoneRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *common.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreatePhoneRecordResponse) Reset() {
	*x = CreatePhoneRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phonebook_phonebook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePhoneRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneRecordResponse) ProtoMessage() {}

func (x *CreatePhoneRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebook_phonebook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneRecordResponse.ProtoReflect.Descriptor instead.
func (*CreatePhoneRecordResponse) Descriptor() ([]byte, []int) {
	return file_phonebook_phonebook_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePhoneRecordResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type QueryPhoneRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *QueryPhoneRecordRequest) Reset() {
	*x = QueryPhoneRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phonebook_phonebook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPhoneRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPhoneRecordRequest) ProtoMessage() {}

func (x *QueryPhoneRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebook_phonebook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPhoneRecordRequest.ProtoReflect.Descriptor instead.
func (*QueryPhoneRecordRequest) Descriptor() ([]byte, []int) {
	return file_phonebook_phonebook_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPhoneRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryPhoneRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *common.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name   string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone  string         `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *QueryPhoneRecordResponse) Reset() {
	*x = QueryPhoneRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phonebook_phonebook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPhoneRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPhoneRecordResponse) ProtoMessage() {}

func (x *QueryPhoneRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebook_phonebook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPhoneRecordResponse.ProtoReflect.Descriptor instead.
func (*QueryPhoneRecordResponse) Descriptor() ([]byte, []int) {
	return file_phonebook_phonebook_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPhoneRecordResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *QueryPhoneRecordResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryPhoneRecordResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_phonebook_phonebook_proto protoreflect.FileDescriptor

var file_phonebook_phonebook_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x18, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x03, 0xe0, 0x41, 0x02, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x43, 0x0a, 0x19, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x32, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6c, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x68, 0x74, 0x74, 0x70, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x62,
	0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phonebook_phonebook_proto_rawDescOnce sync.Once
	file_phonebook_phonebook_proto_rawDescData = file_phonebook_phonebook_proto_rawDesc
)

func file_phonebook_phonebook_proto_rawDescGZIP() []byte {
	file_phonebook_phonebook_proto_rawDescOnce.Do(func() {
		file_phonebook_phonebook_proto_rawDescData = protoimpl.X.CompressGZIP(file_phonebook_phonebook_proto_rawDescData)
	})
	return file_phonebook_phonebook_proto_rawDescData
}

var file_phonebook_phonebook_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_phonebook_phonebook_proto_goTypes = []interface{}{
	(*CreatePhoneRecordRequest)(nil),  // 0: phonebook.CreatePhoneRecordRequest
	(*CreatePhoneRecordResponse)(nil), // 1: phonebook.CreatePhoneRecordResponse
	(*QueryPhoneRecordRequest)(nil),   // 2: phonebook.QueryPhoneRecordRequest
	(*QueryPhoneRecordResponse)(nil),  // 3: phonebook.QueryPhoneRecordResponse
	(*common.Status)(nil),             // 4: common.Status
}
var file_phonebook_phonebook_proto_depIdxs = []int32{
	4, // 0: phonebook.CreatePhoneRecordResponse.status:type_name -> common.Status
	4, // 1: phonebook.QueryPhoneRecordResponse.status:type_name -> common.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_phonebook_phonebook_proto_init() }
func file_phonebook_phonebook_proto_init() {
	if File_phonebook_phonebook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phonebook_phonebook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePhoneRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phonebook_phonebook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePhoneRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phonebook_phonebook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPhoneRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phonebook_phonebook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPhoneRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phonebook_phonebook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_phonebook_phonebook_proto_goTypes,
		DependencyIndexes: file_phonebook_phonebook_proto_depIdxs,
		MessageInfos:      file_phonebook_phonebook_proto_msgTypes,
	}.Build()
	File_phonebook_phonebook_proto = out.File
	file_phonebook_phonebook_proto_rawDesc = nil
	file_phonebook_phonebook_proto_goTypes = nil
	file_phonebook_phonebook_proto_depIdxs = nil
}
